#!/bin/bash

# Функция для рекурсивного импорта секретов с версиями
import_secrets() {
    local path="$1"
    local base_path="$2"
    
    echo "Обработка директории: $path"

    # Рекурсивно обходим все файлы и директории в текущем пути
    for entry in "$path"/*; do
        if [[ -d "$entry" ]]; then
            echo "Найдена директория: $entry"
            # Если это директория, рекурсивно импортируем её содержимое
            import_secrets "$entry" "$base_path"
        fi
    done

    # Получаем список версий, сортируем их и импортируем в правильном порядке
    for entry in $(ls "$path" | grep 'version_' | sort -V); do
        local file_path="$path/$entry"
        echo "Найден файл версии: $file_path"
        # Если это JSON-файл, импортируем его как секрет определенной версии
        local relative_path="${file_path#$base_path/}"
        local secret_path="${relative_path%/version_*}"
        local version="${relative_path#*version_}"
        version="${version%.json}"
        local secret_data=$(jq . "$file_path")

        # Проверка наличия версии секрета в Vault
        if vault kv get -version="$version" "$ROOT_PATH$secret_path" > /dev/null 2>&1; then
            echo "Секрет $secret_path версии $version уже существует, проверка данных..."
            local existing_data=$(vault kv get -version="$version" -format=json "$ROOT_PATH$secret_path" | jq .data.data)
            if [[ "$existing_data" == "$secret_data" ]]; then
                echo "Данные секрета $secret_path версии $version совпадают, пропуск..."
            else
                echo "Данные секрета $secret_path версии $version отличаются, обновление..."
                tmp_file=$(mktemp)
                echo "$secret_data" > "$tmp_file"
                
                vault kv put "$ROOT_PATH$secret_path" @$tmp_file
                if [[ $? -eq 0 ]]; then
                    echo "Секрет из $file_path версии $version успешно обновлен в Vault по пути $ROOT_PATH$secret_path"
                else
                    echo "Ошибка при обновлении секрета из $file_path версии $version в Vault по пути $ROOT_PATH$secret_path" >&2
                fi

                rm "$tmp_file"
            fi
        else
            echo "Импортируем секрет из файла $file_path в путь $ROOT_PATH$secret_path с версией $version"
            tmp_file=$(mktemp)
            echo "$secret_data" > "$tmp_file"
            
            vault kv put "$ROOT_PATH$secret_path" @$tmp_file
            if [[ $? -eq 0 ]]; then
                echo "Секрет из $file_path версии $version успешно импортирован в Vault по пути $ROOT_PATH$secret_path"
            else
                echo "Ошибка при импорте секрета из $file_path версии $version в Vault по пути $ROOT_PATH$secret_path" >&2
            fi

            rm "$tmp_file"
        fi
    done
}

# Указание корневого пути для импорта
IMPORT_DIR="/scr1/Export/"
ROOT_PATH="$kv2/"

# Запуск функции для корневого пути
import_secrets "$IMPORT_DIR" "$IMPORT_DIR"



